Repository drupol/registryonsteroids, pull requests merged in 2018-04, with the labels that each got.

#103 Issue #102: Move file inclusion code section into the class.
  registryonsteroids.module
  src/ThemeRegistryAltererFirst.php
  src/ThemeRegistryAltererLast.php
Labels: Ready to review

#101 Issue #100: Update Runner configuration
  runner.yml.dist
Labels: Ready to review

#99 Issue #98: Fix the typo in the module's name.
  README.md
  registryonsteroids.module
  tests/modules/ros_test/ros_test.info
  tests/themes/ros_theme/ros_theme.info
Labels: Ready to review

#97 Issue #96: Make sure the weight is the heaviest.
  registryonsteroids.install
Labels: Ready to review

#106 Issue #105: Use "alternatives" contrib module is available.
  registryonsteroids.info
Labels: Ready to review

#104 Issue #96: Update module weight
  registryonsteroids.install
Labels: Ready to review

#93 Issue #92: Submodule "registryonsteroids_alter" code cleanup and refactoring.
  modules/registryonsteroids_alter/README.md
  modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc
  modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
  modules/registryonsteroids_alter/registryonsteroids_alter.info
  modules/registryonsteroids_alter/registryonsteroids_alter.module
Labels: Alter submodule, Ready to review, enhancement

#112 Issue #111: Replace ec-europa/qa-automation with drupal/coder.
  composer.json
  ruleset.xml
Labels: Ready to review

#121 Issue #120: Convert arrays to the short syntax.
  modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc
  modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
  modules/registryonsteroids_alter/registryonsteroids_alter.module
  registryonsteroids.admin.inc
  registryonsteroids.install
  registryonsteroids.module
  src/FunctionGroupUtil.php
  src/ThemeHookStub.php
  src/ThemeHookStubFactory.php
  src/ThemeRegistryAltererFirst.php
  tests/modules/ros_test/ros_test.module
  tests/src/Kernel/AbstractThemeTest.php
  tests/src/Kernel/CoreRegistryDefinitionsTest.php
  tests/src/Kernel/RegistryDefinitionsTest.php
Labels: Ready to review

#114 Issue #113: Update documentation, fix typos and function signatures.
  modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc
  registryonsteroids.admin.inc
  registryonsteroids.info
  registryonsteroids.module
Labels: Ready to review

#134 Issue #122: Follow-up
  modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
Labels: Ready to review, bug

#136 Issue #135: Hide the submodule until it's ready.
  modules/registryonsteroids_alter/registryonsteroids_alter.info
Labels: Ready to review

#138 Issue #137: Update the alter hooks mechanisms.
  modules/registryonsteroids_alter/registryonsteroids_alter.alter.inc
  modules/registryonsteroids_alter/registryonsteroids_alter.helpers.inc
Labels: enhancement

#95 Issue #94: Update the README - Avoid confusions with ROS and Drupal's default behavior
  README.md
Labels: Ready to review, enhancement

#128 Issue #127: Implement basic tests for alter submodule.
  tests/fixtures/ros/renderarray/elements.yml
  tests/src/Kernel/AbstractThemeTest.php
  tests/src/Kernel/RenderArrayAlterTest.php
Labels: enhancement

#140 Issue #139: Tests theme hooks (and variants) using theme functions.
  tests/fixtures/core/registry/registry.yml
  tests/fixtures/core/render/render.yml
  tests/fixtures/ros/registry/intermediate.yml
  tests/fixtures/ros/registry/registry.yml
  tests/fixtures/ros/render/render.yml
  tests/modules/ros_test/ros_test.module
  tests/src/Kernel/AbstractThemeTest.php
  tests/themes/ros_theme/template.php
Labels: Ready to review

#142 Issue #141: Set Registry on steroids a dependency of ROS Alter submodule and remove the hidden property.
  modules/registryonsteroids_alter/registryonsteroids_alter.info
Labels: Ready to review
