Repository drupol/registryonsteroids, pull requests merged in 2018-03, with the labels that each got.

#42 #41: Add line breaks in theme output in RegistryDefinitionsTest::testPreprocessProcessCascade().
  tests/src/Kernel/RegistryDefinitionsTest.php
Labels: Ready to merge

#49 #41: more linebreaks in yml
  tests/fixtures/core/render/render.yml
  tests/fixtures/ros/render/render.yml
  tests/src/Kernel/CoreRegistryDefinitionsTest.php
  tests/src/Kernel/RegistryDefinitionsTest.php
Labels: Ready to merge

#53 #41 ff: (test) Add assertEqualThemeRegistryEntries().
  tests/src/Kernel/AbstractThemeTest.php
  tests/src/Kernel/CoreRegistryDefinitionsTest.php
  tests/src/Kernel/RegistryDefinitionsTest.php
Labels: Ready to merge

#55 Issue #54: Uses arrays instead of strings for comparisons in tests.
  tests/fixtures/core/registry/registry.yml
  tests/fixtures/core/render/render.yml
  tests/fixtures/ros/registry/registry.yml
  tests/fixtures/ros/render/render.yml
  tests/modules/ros_test/ros0.tpl.php
  tests/modules/ros_test/ros1.tpl.php
  tests/modules/ros_test/ros_test.module
  tests/src/Kernel/CoreRegistryDefinitionsTest.php
  tests/src/Kernel/RegistryDefinitionsTest.php
  tests/themes/ros_theme/ros2.tpl.php
  tests/themes/ros_theme/template.php
Labels: Ready to review

#57 #56: tests append template or theme function
  tests/fixtures/core/render/render.yml
  tests/fixtures/ros/render/render.yml
  tests/modules/ros_test/ros0.tpl.php
  tests/modules/ros_test/ros1.tpl.php
  tests/themes/ros_theme/ros2.tpl.php
Labels: Ready to merge

#65 Issue #64: Include a patch to prevent warnings with PHP 7.2.
  composer.json
Labels: Ready to merge

#70 Issue #69: Update the configuration files of Travis and Runner
  .travis.yml
  runner.yml.dist
  tests/src/Kernel/AbstractThemeTest.php
Labels: Ready to review

#68 Issue #67: Move code from global scope into a hook function.
  registryonsteroids.module
Labels: Ready to review

#77 Issue #76: Introduce a ThemeRegistryAltererInterface interface and 2 new classes to defer the the mechanisms into objects.
  registryonsteroids.module
  src/FunctionGroupUtil.php
  src/ThemeHookStub.php
  src/ThemeHookStubFactory.php
  src/ThemeRegistryAltererFirst.php
  src/ThemeRegistryAltererInterface.php
  src/ThemeRegistryAltererLast.php
Labels: Ready to review

#73 Issue #71: Move xautoload module from require to require-dev section.
  composer.json
Labels: Ready to review

#79 Issue #78: Update patch for PHP 7.2.
  composer.json
Labels: Ready to review

#81 Issue #80: Cleanup the composer.json file.
  composer.json
Labels: Ready to review

#45 Issue #44: Update README.md, add steps to reproduce the issue locally…
  README.md
Labels: Ready to review

#85 Hide submodule and update README.
  README.md
  modules/registryonsteroids_alter/registryonsteroids_alter.info
Labels: Ready to review

#87 Issue #86: Update url to patch.
  composer.json
Labels: Ready to review

#91 Issue #90: Update patch for PHP 7.2.
  composer.json
Labels: Ready to review

#89 Issue #88: Let our render array alterations run after those from other modules.
  modules/registryonsteroids_alter/registryonsteroids_alter.module
Labels: Alter submodule, Ready to review
